version: 2

jobs:
  lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm ci
      - run: cd demo && npm ci && cd -
      - run: npm run lint

  typescript:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm ci
      - run: npm run check-types

  format:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm ci
      - run: npm run check-format

  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm ci
      - run: npm test -- --coverage
      - run: bash <(curl -s https://codecov.io/bash) -f
          ./coverage/coverage-final.json

workflows:
  version: 2
  build:
    jobs:
      - lint
      - typescript
      - format
      - test
